### ISSUE TITLE
Pitch too high when compiling source code

### ISSUE THREAD

**Issue by makeitsquare** [udiazr/f401cc-audio#1]
Hi,
you binary works great on my STM32F401CEU black pill, but when I compile your source code in STM32CubeIDE/MX, the audio pitch is too high and the sound is a bit distorted. Could you please post your clock configuration? Mine (which doesn't work correctly) is attached.
Thanks!
![Screen Shot 2022-10-16 at 12 19 53 PM](https://user-images.githubusercontent.com/84725204/196046607-c9dfab58-ef83-42a7-8a4a-339f7dd675da.png)

**Comment by udiazr** [comment]
Apparently it is the same clock configuration
I forgot to upload all files, but in :
STM32_USB_Device_Library/Class/AUDIO/Inc/usbd_audio.h 

The PWM buffer size  must be an integer multiple of AUDIO_TOTAL_BUF_SIZE, if not you get some distortion:
#define AUDIO_OUT_PACKET                              (uint16_t)(((USBD_AUDIO_FREQ * 2U * 2U) / 1000U))
#define AUDIO_OUT_PACKET_NUM                          32U
#define AUDIO_TOTAL_BUF_SIZE                          ((uint16_t)(AUDIO_OUT_PACKET * AUDIO_OUT_PACKET_NUM))

by default AUDIO_OUT_PACKET_NUM is 80U  and is too big (you had problems to allocate memory, didn't you?)

I won't work in the same code anymore. I'm rewriting this program to make it 3rd order, to work at 120MHz (overclock) and to make it cleaner. I think that will be enough to push the audio quality higher to be bounded not by the digital processing but the electrical noise (crosstalk, switching noise,power supply noise), please wait a few weeks.

**Comment by makeitsquare** [comment]
Thanks for the reply. I am a bit embarrassed, the problem wasn't the clock configuration, but the USB Audio Device Class configuration. I missed that there is USBD_AUDIO_FREQ parameter which defaults to 22100 samples/s. After I changed this to 48000 sample/s as you indicated in the READEME.md, the pitch is right and the distortion is gone.

My device is a STM32f401CEU which has 96 kB of ram and therefore it compiles fine with AUDIO_OUT_PACKET_NUM  set to 80 (also there is no change in pitch if I change this from 80 to 32...). If I change the device to your STM32f401CCU, I get an error that the RAM overflows by 2896 bytes. Changing AUDIO_OUT_PACKET_NUM to 32 fixes that.

**Comment by udiazr** [comment]
Hi, I've updated the code. Now it works at 120MHz 2nd order yet, OSR=10 but sound clearer. I tested a 3rd order in one channel and I cannot tell the difference because I have too much noise (powersupply, crosstalk) . I'm working in a protoboard.
